name: Deploy to Github Pages
on:
  push:
    branches:
      - staging
jobs:
  github-deploy:
    name: Deploying to master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "nsnyder"
          git config user.email "nathan@snydern.com"
          npm run github-deploy