name: Deploy to Github pages
on:
  push:
    branches:
      - staging
jobs:
  github-deploy:
    name: Deploying to master
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "nsnyder" && git config user.email "nathan@snydern.com"
          npm run github-deploy
      - name: get commit message
        run: |
           echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ GITHUB_SHA }})
      - name: "Tell IFTTT when the site is deployed"
        uses: cixo/ifttt-trigger@v0.3
        with:
          key: "${{ secrets.IFTTT_KEY }}"
          event: "site_deployed"
          value1: "https://www.snydern.com"
          value2: "${{ env.commitmsg }}"